### ISSUE TITLE
OpenLabとの同期

### ISSUE THREAD

**Issue by yutopia** [skk-dev/dict#1]
とりあえず問題提起だけしておきます。

元々は GitHubで一元的に辞書も管理してしまおうというのがアイディアですが、現状では OpenLab のオリジナルとの辞書との同期は手動で行わなければいけません。
GitHubに対しての改変にしても本家の改変に対してもです。
なんとかこの同期を自動化が必要かなぁ、と。
OpenLabの辞書登録フォームの動作不良の問題もありますし。

**Comment by ohaguro** [comment]
openlab版の辞書は更新停止が宣言されたので、同期する必要は消滅したのでは？
