### ISSUE TITLE
IssuesやPull requestsがすべて消えている

### ISSUE THREAD

**Issue by ohaguro123** [skk-dev/dict#1]
以前あったIssuesやPull requestsがすべて消えていて見えないのですがこれは所謂おま環なのでしょうか？

**Comment by ohaguro123** [comment]
ログアウトした状態でもすべて消えていた

**Comment by yutopia** [comment]
skk-dev/dictが一度削除されてしまったらしいです。

**Comment by conao3** [comment]
申し訳ありません、私の誤操作です。
READMEへの追記にて周知が遅れておりました。帰宅後対処します。

**Comment by conao3** [comment]
追記しました。この度は本当に申し訳ありません。チームの皆さんとcontributer, プロジェクトに関わるすべての方にお詫びします。
このissueはcloseします。
