### ISSUE TITLE
辞書登録・削除希望単語入力フォームは閉鎖してはどうか

### ISSUE THREAD

**Issue by ohaguro** [skk-dev/dict#15]
openlabとgithabでの辞書の同期を止め、更新はgithub上のみの状態でopenlab上の辞書登録・削除希望単語入力フォームで辞書校正を受理するというのは現状に合わないように思います。辞書登録・削除希望単語入力フォームは閉鎖したほうが良いのでは？
また
http://openlab.ring.gr.jp/skk/dic-ja.html
http://openlab.ring.gr.jp/skk/wiki/wiki.cgi?page=FrontPage
についても辞書登録・削除希望単語入力フォームではなくgithubのIssuesなりPull requestsに誘導するのが望ましいように感じます。

**Comment by conao3** [comment]
@kyohsuke, @myuhe, @tats, @tkita, @yutopia 
ご存知そうな方にメンションします。このissueちょっと進めたいです。

具体的には http://openlab.ring.gr.jp/skk/wiki/wiki.cgi?page=SKK%BC%AD%BD%F1 のページにこのレポジトリへのリンクを貼り、ユーザーを誘導したいです。
現在 openlab.ring.gr.jp にアクセス権を持っておられる方はおられますでしょうか？

**Comment by kyohsuke** [comment]
> 現在 openlab.ring.gr.jp にアクセス権を持っておられる方はおられますでしょうか？

自分は持ってないです、申し訳ないです。

**Comment by yutopia** [comment]
おおむらです。

しばらく何も追えていないのですが……。

openlab のページですが、記憶ではwebのテンプレートみたいなものを cvs でcommit しないといけなかった気がします。
中で結構複雑なcronが動いていて、ファイルを直接書き換えようとしてもcvsリポジトリの内容で上書きされてしまったような………。
実際、今入って見たところ現在進行形でページは更新され続けているようです。(最近では9/11のだった。)
cvsのレポジトリをcheckout しようとしましたがうまくいきませんでした。

件のページはWikiで管理されているのでcvsとは別だったかもしれませんが、作成者以外はパーミッションが無いので変更が効かなかったりします。
Wiki自身はWIki編集用のIDがあれば編集できるのでしょうが、私は持っていません。
日付は2015年から更新されてないっぽいです。
ログだけは生きてるみたいです。

それが理由で色々とopenlag から GitHubに移行したのでした。

登録そのものをGitHubでクローズできるようにしたい、というのもありましたが、今のところうまく行ってなかったのでは。

2021年9月15日(水) 21:45 Naoya Yamashita ***@***.***>:

> @kyohsuke <https://github.com/kyohsuke>, @myuhe <https://github.com/myuhe>,
> @tats <https://github.com/tats>, @tkita <https://github.com/tkita>,
> @yutopia <https://github.com/yutopia>
> ご存知そうな方にメンションします。このissueちょっと進めたいです。
>
> 具体的には http://openlab.ring.gr.jp/skk/wiki/wiki.cgi?page=SKK%BC%AD%BD%F1
> のページにこのレポジトリへのリンクを貼り、ユーザーを誘導したいです。
> 現在 openlab.ring.gr.jp にアクセス権を持っておられる方はおられますでしょうか？
>
>
>

**Comment by nathancorvussolis** [comment]
wikiのアカウントを以前もらっていたのでSKK辞書のトップに追記してみました。

http://openlab.ring.gr.jp/skk/wiki/wiki.cgi?page=SKK%BC%AD%BD%F1

FrontPageはメニューに編集が表示されないのでウェブ上からだと更新できないみたいです…

文言に意見があれば教えてください。

**Comment by conao3** [comment]
@yutopia さん、ありがとうございます。
なかなかに闇な状況ですね。。openlabはこのまま弄らずに放置というのが安全策なんですかね。。

---
@nathancorvussolis さん、ありがとうございます。
なんとWikiのアカウントを持っている方がいるなんて。。
> 「SKK 辞書の誤り、追加すべき候補、エントリを発見された方は多少にかかわらず、辞書登録・削除希望入力フォームを利用して入力いただくか、mailto:skk@ring.gr.jp までお知らせください。」

ここらへんも文面とリンクを整備したいのですがお願いできますか？それともアカウントが払い出せる状況でしたら私も編集できるようにしてもらえれば私も手伝うことができます。

**Comment by ohaguro** [comment]
あら復活している。提案者です。この話題はhttps://github.com/skk-dev/temp_web/issues/9 にて改めて提起しています。同じ話題があちこちに分散すると追いにくくなるので、こちらは一度閉じたいと思います。
