### ISSUE TITLE
SKK-JISYO.edict license is DFSG-incompatible

### ISSUE THREAD

**Issue by tats** [skk-dev/dict#17]
Quoting from [skk 6904]:
> Date: Thu, 27 Mar 2008 03:49:53 +0900 (JST)
> From: Kobayashi Noritada <nori1@dolphin.c.u-tokyo.ac.jp>
> Subject: [skk 6904] EDICT のライセンス変更を受けての SKK-JISYO.edict に関する提案
> To: skk@ring.gr.jp
> 
> EDICT は何回かライセンスを変更しているようですが、少し前まで Creative
> Commons Attribution-ShareAlike Licence (CC by-sa) 2.5 だったのが、先日 
> CC by-sa 3.0 になりました[1]。
> 
> SKK 辞書に含まれる EDICT は、ヘッダを見るかぎりその前の独自ライセンス
> 時代のもののように思われますが、もしよろしければ、EDICT を最新版に追従
> するとともに、ライセンスまわり (SKK-JISYO.edict のヘッダ・
> edict_doc.txt・READMEs/committers.txt) も更新されては如何でしょうか?
> edict_doc.txt は現在は 
> http://ftp.monash.edu.au/pub/nihongo/edict_doc.html となっており、ライ
> センスに関する記述の実体は 
> http://www.csse.monash.edu.au/~jwb/edrdg/licence.html にあるようです。
> 
> 特に急がなければならないというわけでもないので、お時間のあるときにでも
> ご検討願えたらと思います。
> 
> [1] http://www.csse.monash.edu.au/~jwb/edrdg/licence.html

現状のSKK-JISYO.edictは、その有償配布制限から、Debian Free Software
Guidelines (DFSG)に適合しないものとして、Debianのskkdicパッケージ
からは除外しています。

もしCC by-sa 3.0が適用されるなら、DFSG適合として、Debianのskkdic
パッケージに収録しようと思います。

**Comment by tkita** [comment]
手元で、CC by-sa 3.0 版 edict ベースで SKK-JISYO.edict を作り直しましたが、ファイル冒頭の著作権表示をどう書けばよいかアドバイスいただけるでしょうか。
https://gist.github.com/tkita/1c2ccca1c50ac2383fcc873786394532

**Comment by tats** [comment]
あとは、CC BY-SA 3.0のURLを明示しておいてはどうでしょうか。

```
;;     Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)
;;     <https://creativecommons.org/licenses/by-sa/3.0/deed>
;;     <https://creativecommons.org/licenses/by-sa/3.0/legalcode>
```

**Comment by tkita** [comment]
ありがとうございます。
push しました。

**Comment by tats** [comment]
Thank you.  Closing.
