### ISSUE TITLE
SKK-JISYO.emoji is not distributable

### ISSUE THREAD

**Issue by tats** [skk-dev/dict#18]
SKK-JISYO.emojiについて、手元で生成して使うだけなら問題なさそう
ですが、ライセンスがはっきりせず再配布には向かないのが現状だと
思います。

派生作品への許可が見あたらない
<https://unicode.org/emoji/charts-13.0/emoji-list.html>
ではなく<https://unicode.org/Public/emoji/>配下等、
Unicode Data Files and Software Licenseの範疇のファイルから
生成できれば、EDICTのCC BY-SAとも矛盾せずに配布できそうです。

cf. https://www.gnu.org/licenses/license-list.ja.html#Unicode
    https://www.unicode.org/license.html
    https://www.unicode.org/copyright.html

**Comment by tkita** [comment]
コメントありがとうございます。
私も、emoji.el を作っていた最中からそのような気がしていました（ライセンス関係）ので、いまのところ SKK-JISYO.emoji そのものは配布物とはしていません。
Public/emoji/配下のファイルは知っていてひととおり見ていたのですが、キーワードに相当するフィールドが無いため、私が望んでいた絵文字辞書を作るのに emoji-list.html を選択したのでした。
ただ、せっかくですので、Public/emoji/配下のファイルを基に生成するよう変えようと思います。

**Comment by tkita** [comment]
CLDR 配下の annotations が使えそうです。
http://unicode.org/Public/cldr/

**Comment by tkita** [comment]
いったん push しました。 6d37de です。
TODO ありますので、気長に作業します。

**Comment by tats** [comment]
Thanks for updating the Unicode dictionary files.  I'll package them
in the Debian skkdic package.

BTW, Could you please add the `-*-coding: utf-8-*-` header to the files?

**Comment by tkita** [comment]
速やかにやっておきます。

**Comment by tkita** [comment]
push しました。

**Comment by tats** [comment]
ありがとうございます。

**Comment by tats** [comment]
SKK-JISYO.emoji, SKK-JISYO.edict2 and SKK-JISYO.ivd are in Debian unstable now.
Will be included in Debian 11 "bullseye".
cf. https://tracker.debian.org/pkg/skkdic

**Comment by tkita** [comment]
👍
