### ISSUE TITLE
Invalid entry in SKK-JISYO.L

### ISSUE THREAD

**Issue by tani** [skk-dev/dict#24]
Hi, there. I found lacking character `/` at the following lines in SKK-JISYO.L

sars-cov /severe acute respiratory syndrome coronavirus/SARSコロナウイルス
sars-cov-2 /severe acute respiratory syndrome coronavirus 2/2019新型コロナウイルス

The above lines should be the follows

sars-cov /severe acute respiratory syndrome coronavirus/SARSコロナウイルス/
sars-cov-2 /severe acute respiratory syndrome coronavirus 2/2019新型コロナウイルス/

Please update them. Thanks!

**Comment by tkita** [comment]
fix it.
thanks!

**Comment by tani** [comment]
Thanks!
