### ISSUE TITLE
GitHub Pages 側の辞書が更新されていない

### ISSUE THREAD

**Issue by rinsuki** [skk-dev/dict#42]
表題の通り、GitHub Pages 側の辞書が2020年のコミット https://github.com/skk-dev/dict/commit/38c81dbc74cdbdead843364023dea837f239a48c を最後に、3年ほど更新されてないように見えます。

何か理由があって更新していないのならそれはそれで良いのですが、単に理由なく更新されていないのであれば GitHub Actions での生成に切り替えるなども手かと思います (cf. https://github.com/actions/upload-pages-artifact ) 。

**Comment by tkita** [comment]
更新しました。
なお、私自身は GitHub Actions は理解していないのですが、配布版ファイルの生成を自動化することは賛成です。
（野良 make に固執している訳ではありません）
自動化するよう PR いただけると幸いです。
