### ISSUE TITLE
「﨑」の辞書への登録

### ISSUE THREAD

**Issue by yuttie** [skk-dev/dict#46]
「﨑」が変換に出てきませんでしたので、ご登録頂けないでしょうか？
リポジトリ内およびIssuesを検索してヒットしないようでしたので、新規に立てています。
よろしくお願い致します。

**Comment by yuttie** [comment]
あっ、もしかして辞書はeuc-jpなので、エンコーディング的に不可能だから登録されていない（登録できない）ということでしょうか？

**Comment by krisfail** [comment]
`﨑`はJIS第三水準の文字なので、`SKK-JISYO.JIS3_4`の辞書に収録されています。GitHubが対応していないからか検索にはかかりませんが、一般的なSKK実装では問題なく使えると思います。

**Comment by yuttie** [comment]
@krisfail ありがとうございます！そちらの辞書を試してみます。
